directories:
  output: release
  buildResources: build
appId: com.hurufa.fontfinder
productName: Hurufa
mac:
  category: public.app-category.utilities
  target:
    - dmg
    - zip
  icon: src/assets/icons/icon.icns
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.plist
  artifactName: ${productName}-${version}-${arch}.${ext}
  strictVerify: false
  identity: null
  asarUnpack: '**/node_modules/**/*.node'
  minimumSystemVersion: 10.13.0
  darkModeSupport: true
  notarize: false
win:
  target:
    - nsis
    - zip
  icon: src/assets/icons/icon.ico
linux:
  target:
    - AppImage
    - deb
    - rpm
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
publish:
  provider: github
  owner: mhadimedia
  repo: Hurufa-Font-Finder
electronVersion: 29.4.6
